# Generated by Django 4.0.2 on 2022-03-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_src', models.URLField()),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('current_auction_price', models.FloatField()),
                ('time_created', models.CharField(max_length=11)),
                ('auction_time_limit', models.CharField(max_length=11)),
                ('gender', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=10)),
                ('listing_id', models.CharField(max_length=100)),
            ],
        ),
    ]
